import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header";
import Nav from '../components/Nav';
import Results from '../components/Results';
import requests from '../utils/requests';
import _ from 'lodash';

export default function Home({results}) {
  // console.log(props)
  return (
    <div >
      <Head>
        <title>Hulu Michael Monteiro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* Header */}
    <Header />

    {/* Nav */}
    <Nav />

    {/* Results */}
    <Results />

    </div>
  )
}
function prepareForSerializatoin(obj) {
  return obj.mapValues(obj, value => typeof value === 'undefined' ? null : value);
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) =>  res.json());
     
   return prepareForSerializatoin({
    props: {
      results: request.results,
    },
  });
}
//server side stuff. This gets exexuted before the rest of the code gets executed, because it is a server side render which is also a lot quicker
